name: CI (Continuous Integration)

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build and Run Container
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%s')"
      
    - name: Build and Run the Docker Image
      env:
        DATES: ${{ steps.date.outputs.date }}
      run: |
        docker build -t rahilwisdom/flaskimages:$DATES .
        docker run -d --name flask-container -p 5000:5000 rahilwisdom/flaskimages:$DATES

  test:
    name: Testing
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%s')"
      
    - name: Build and Run the Docker Image
      env:
        DATES: ${{ steps.date.outputs.date }}
      run: |
        docker build -t rahilwisdom/flaskimages:$DATES .
        docker run -d --name flask-container -p 5000:5000 rahilwisdom/flaskimages:$DATES

    - name: Install Dependencies For Testing
      run: |
        pip install -r requirements.txt
        
    - name: Testing
      run: |
        python3 test_app.py