name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build and Run Container
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%s')"
      
    - name: Build the Docker image
      env:
        DATES: ${{ steps.date.outputs.date }}
      run: |
        docker build -t rahilwisdom/flaskimages:$DATES .
        docker run -d --name flask-container -p 5000:5000 rahilwisdom/flaskimages:$DATES

  test:
    name: Testing
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%s')"
      
    - name: Build the Docker image
      env:
        DATES: ${{ steps.date.outputs.date }}
      run: |
        docker build -t rahilwisdom/flaskimages:$DATES .
        docker run -d --name flask-container -p 5000:5000 rahilwisdom/flaskimages:$DATES
        docker container ls

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Testing
      run: |
        python3 test_app.py

  merge:
    name: Automated merge if pass
    runs-on: ubuntu-latest
    needs: test

    steps: 
    - uses: actions/checkout@v3
    - name: Merge pull request (if tests pass)
      if: ${{ github.event.pull_request.merged == true }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout main
        git merge --no-ff ${{ github.head_ref }}
        git push -u origin main
