name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DATES: $(date +%s)
      run: |
        docker build -t rahilwisdom/flaskimages:1.0 .
        docker images
