name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -t rahilwisdom/flaskimages:${{ steps.date.outputs.date }}
        docker images
        docker run --name Flask-container -p 5000:5000 rahilwisdom/flaskimages:${{ steps.date.outputs.date }}
