name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DATES: $(date +%s)
      run: |
        docker build -t rahilwisdom/flaskimages:$DATES .
        docker images
        docker run --name flaskcontainer -p 5000:5000 rahilwisdom/flaskimages:$DATES
