name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build and Run Container
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%s')"
      
    - name: Build the Docker image
      env:
        DATES: ${{ steps.date.outputs.date }}
      run: |
        docker build -t rahilwisdom/flaskimages:$DATES .
        docker run -d --name flask-container -p 5000:5000 rahilwisdom/flaskimages:$DATES

  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Get list of container
        run: |
          docker container ls
